export const industrySkills = [
  {
    name: "Software Developer",
    skills: [
      "JavaScript",
      "TypeScript",
      "React",
      "Node.js",
      "Git",
      "Problem Solving",
      "Data Structures",
      "Algorithms",
      "API Design",
      "Testing",
    ],
  },
  {
    name: "Frontend Developer",
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "React.js",
      "Next.js",
      "Responsive Web Design",
      "UI/UX Design",
      "Chakra UI",
      "Mantine UI",
      "Styled Components",
      "Cross-browser Compatibility",
    ],
  },
  {
    name: "Full Stack Developer",
    skills: [
      "JavaScript",
      "Node.js",
      "React",
      "Express",
      "RESTful APIs",
      "GraphQL",
      "Database Management",
      "AWS",
      "Git",
      "Testing",
    ],
  },
  {
    name: "Mobile Developer",
    skills: [
      "React Native",
      "JavaScript",
      "iOS",
      "Android",
      "Mobile UI/UX",
      "Performance Optimization",
      "API Integration",
      "Cross-platform Development",
    ],
  },
  {
    name: "Data Scientist",
    skills: [
      "Python",
      "R",
      "Statistics",
      "Machine Learning",
      "SQL",
      "Data Visualization",
      "Big Data",
      "Data Cleaning",
      "Jupyter Notebooks",
      "Experimental Design",
    ],
  },
  {
    name: "AI Research Scientist",
    skills: [
      "Machine Learning",
      "Deep Learning",
      "Algorithm Development",
      "Python",
      "TensorFlow",
      "PyTorch",
      "Statistical Analysis",
      "Data Mining",
      "Research",
      "Innovation",
    ],
  },
  {
    name: "Cybersecurity Analyst",
    skills: [
      "Network Security",
      "Ethical Hacking",
      "Risk Assessment",
      "Incident Response",
      "Threat Analysis",
      "Security Auditing",
      "Penetration Testing",
      "Encryption",
      "Firewalls",
      "Compliance",
    ],
  },
  {
    name: "Business Analyst",
    skills: [
      "Data Analysis",
      "Process Improvement",
      "Requirements Gathering",
      "Stakeholder Engagement",
      "Modeling",
      "Reporting",
      "Critical Thinking",
      "Communication",
      "Problem Solving",
      "Agile Methodologies",
    ],
  },
  {
    name: "IT Project Manager",
    skills: [
      "Project Management",
      "Resource Allocation",
      "Scheduling",
      "Risk Management",
      "Team Leadership",
      "Agile/Scrum",
      "Budgeting",
      "Communication",
      "Problem Solving",
      "Stakeholder Management",
    ],
  },
  {
    name: "Cloud Engineer",
    skills: [
      "AWS",
      "Serverless Functions",
      "GraphQL API Management",
      "Cloud Deployments",
      "Infrastructure as Code",
      "Security",
      "Monitoring",
      "Automation",
      "Scalability",
      "CI/CD",
    ],
  },
  {
    name: "Network Engineer",
    skills: [
      "Routing",
      "Switching",
      "Network Protocols",
      "WAN/LAN",
      "Troubleshooting",
      "Security",
      "Configuration",
      "Cisco",
      "Juniper",
      "Firewall Management",
    ],
  },
  {
    name: "Mechanical Engineer",
    skills: [
      "Mechanics",
      "Thermodynamics",
      "Fluid Mechanics",
      "Materials Science",
      "CAD",
      "Structural Analysis",
      "Prototyping",
      "Testing",
      "Problem Solving",
      "Manufacturing Processes",
    ],
  },
  {
    name: "Electrical Engineer",
    skills: [
      "Circuit Design",
      "Signal Processing",
      "Control Systems",
      "Embedded Systems",
      "Microelectronics",
      "Power Systems",
      "PCB Design",
      "Troubleshooting",
      "Simulation",
      "Instrumentation",
    ],
  },
  {
    name: "Civil Engineer",
    skills: [
      "Structural Analysis",
      "Project Management",
      "Geotechnical Engineering",
      "Construction Management",
      "Surveying",
      "Design Standards",
      "Material Science",
      "Risk Assessment",
      "Sustainability",
      "Urban Planning",
    ],
  },
  {
    name: "Financial Analyst",
    skills: [
      "Financial Modeling",
      "Excel",
      "Accounting",
      "Data Analysis",
      "Forecasting",
      "Market Analysis",
      "Budgeting",
      "Reporting",
      "Risk Management",
      "Corporate Finance",
    ],
  },
];

export const courses = [
  // Computer Science & Information Technology (Undergraduate)
  {
    code: "CS101",
    name: "Introduction to Computer Science",
    skills: [
      "Programming Fundamentals",
      "Problem Solving",
      "Algorithms",
      "Data Structures",
    ],
  },
  {
    code: "CS201",
    name: "Web Development",
    skills: ["HTML", "CSS", "JavaScript", "React", "Node.js"],
  },
  {
    code: "CS301",
    name: "Database Systems",
    skills: ["SQL", "Database Design", "Data Modeling", "NoSQL"],
  },
  {
    code: "CS401",
    name: "Advanced Software Engineering",
    skills: [
      "Design Patterns",
      "Software Architecture",
      "Testing",
      "Agile Methodologies",
    ],
  },
  {
    code: "SE101",
    name: "Software Engineering Fundamentals",
    skills: [
      "Software Development Lifecycle",
      "Requirements Engineering",
      "Version Control",
      "Team Collaboration",
    ],
  },
  // Data Science & Analytics (Undergraduate & Postgraduate)
  {
    code: "DS101",
    name: "Introduction to Data Science",
    skills: ["Python", "Statistics", "Data Visualization", "Data Cleaning"],
  },
  {
    code: "DS201",
    name: "Machine Learning",
    skills: [
      "Machine Learning",
      "Python",
      "Supervised Learning",
      "Unsupervised Learning",
    ],
  },
  {
    code: "DA101",
    name: "Data Analytics and Visualization",
    skills: [
      "Data Mining",
      "Advanced Statistics",
      "Data Visualization",
      "R Programming",
    ],
  },
  // Artificial Intelligence & Cyber Security (Postgraduate)
  {
    code: "AI501",
    name: "Master of Science in Artificial Intelligence",
    skills: [
      "Machine Learning",
      "Deep Learning",
      "Natural Language Processing",
      "Algorithm Development",
    ],
  },
  {
    code: "CY501",
    name: "Master of Science in Cyber Security",
    skills: [
      "Network Security",
      "Ethical Hacking",
      "Risk Assessment",
      "Incident Response",
    ],
  },
  // Engineering Courses (Undergraduate)
  {
    code: "EE101",
    name: "Introduction to Electrical Engineering",
    skills: [
      "Circuit Analysis",
      "Electronics",
      "Signal Processing",
      "Embedded Systems",
    ],
  },
  {
    code: "ME101",
    name: "Fundamentals of Mechanical Engineering",
    skills: ["Statics", "Dynamics", "Thermodynamics", "Materials Science"],
  },
  {
    code: "CE101",
    name: "Foundations of Civil Engineering",
    skills: [
      "Structural Analysis",
      "Geotechnical Engineering",
      "Construction Management",
      "Materials",
    ],
  },
  // Business & Management (Undergraduate & Postgraduate)
  {
    code: "EC101",
    name: "Introduction to Economics",
    skills: [
      "Microeconomics",
      "Macroeconomics",
      "Quantitative Analysis",
      "Critical Thinking",
    ],
  },
  {
    code: "MBA101",
    name: "Master of Business Administration",
    skills: [
      "Leadership",
      "Strategic Planning",
      "Financial Analysis",
      "Organizational Behavior",
    ],
  },
  // Information Technology & Cyber Management
  {
    code: "IT101",
    name: "Information Technology Fundamentals",
    skills: [
      "Networking",
      "Database Systems",
      "Programming",
      "Cyber Security Basics",
    ],
  },
  // Digital Marketing & Creative Media
  {
    code: "MK101",
    name: "Digital Marketing Fundamentals",
    skills: ["SEO", "SEM", "Social Media Marketing", "Content Marketing"],
  },
  {
    code: "CM101",
    name: "Creative Media and Design",
    skills: [
      "Graphic Design",
      "Digital Imaging",
      "User Experience",
      "Visual Communication",
    ],
  },
];
