export const industrySkills = [
  {
    name: "Software Developer",
    skills: [
      "JavaScript",
      "TypeScript",
      "React",
      "Node.js",
      "Git",
      "Problem Solving",
      "Data Structures",
      "Algorithms",
      "API Design",
      "Testing",
    ],
  },
  {
    name: "Data Scientist",
    skills: [
      "Python",
      "R",
      "Statistics",
      "Machine Learning",
      "SQL",
      "Data Visualization",
      "Big Data",
      "Data Cleaning",
      "Jupyter Notebooks",
      "Experimental Design",
    ],
  },
  {
    name: "UX Designer",
    skills: [
      "User Research",
      "Wireframing",
      "Prototyping",
      "Figma",
      "Adobe XD",
      "Usability Testing",
      "Information Architecture",
      "Design Thinking",
      "Accessibility",
      "Visual Design",
    ],
  },
  {
    name: "Product Manager",
    skills: [
      "Product Strategy",
      "User Stories",
      "Roadmapping",
      "Agile Methodologies",
      "Market Research",
      "Stakeholder Management",
      "Data Analysis",
      "Prioritization",
      "Communication",
      "Leadership",
    ],
  },
  {
    name: "Digital Marketing Specialist",
    skills: [
      "SEO",
      "SEM",
      "Social Media Marketing",
      "Content Marketing",
      "Email Marketing",
      "Analytics",
      "A/B Testing",
      "Campaign Management",
      "CRM",
      "Copywriting",
    ],
  },
];

export const courses = [
  {
    code: "CS101",
    name: "Introduction to Computer Science",
    skills: [
      "Programming Fundamentals",
      "Problem Solving",
      "Algorithms",
      "Data Structures",
    ],
  },
  {
    code: "CS201",
    name: "Web Development",
    skills: ["HTML", "CSS", "JavaScript", "React", "Node.js"],
  },
  {
    code: "CS301",
    name: "Database Systems",
    skills: ["SQL", "Database Design", "Data Modeling", "NoSQL"],
  },
  {
    code: "DS101",
    name: "Introduction to Data Science",
    skills: ["Python", "Statistics", "Data Visualization", "Data Cleaning"],
  },
  {
    code: "DS201",
    name: "Machine Learning",
    skills: [
      "Machine Learning",
      "Python",
      "Supervised Learning",
      "Unsupervised Learning",
    ],
  },
  {
    code: "UX101",
    name: "User Experience Design",
    skills: [
      "User Research",
      "Wireframing",
      "Prototyping",
      "Usability Testing",
    ],
  },
  {
    code: "PM101",
    name: "Product Management Fundamentals",
    skills: [
      "Product Strategy",
      "User Stories",
      "Roadmapping",
      "Agile Methodologies",
    ],
  },
  {
    code: "MK101",
    name: "Digital Marketing Fundamentals",
    skills: ["SEO", "SEM", "Social Media Marketing", "Content Marketing"],
  },
];
